"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Product = { id:string; name:string; slug:string; category:string; brandId:string|null; categoryId:string|null; series:string; sku:string; capacity:string; energyClass:string; wifi:string; stock:number; price:number; status:string; saleMode:string; description:string; imageUrl:string };
type ServiceRequest = { id:string; requestNumber:string; type:string; name:string; phone:string; city:string; message:string; status:string; createdAt:string };
type Order = { id:string; orderNumber:string; customerName:string; total:number; status:string; createdAt:string };
type SecondHand = {id:string;name:string;slug:string;category:string;condition:string;testNotes:string;warranty:string;price:number;stock:number;imageUrl:string;status:string;description:string};
type Post = {id:string;title:string;slug:string;excerpt:string;content:string;imageUrl:string;status:string};
type Taxonomy = {id:string;name:string;slug:string;active:boolean};
const initial = { name:"", slug:"", category:"Klima", brandId:null as string|null, categoryId:null as string|null, series:"", sku:"", capacity:"", energyClass:"", wifi:"", price:0, stock:0, saleMode:"quote", status:"draft", description:"", imageUrl:"" };
const secondInitial={name:"",slug:"",category:"Klima",condition:"İyi",testNotes:"",warranty:"",price:0,stock:1,imageUrl:"",status:"draft",description:""};
const postInitial={title:"",slug:"",excerpt:"",content:"",imageUrl:"",status:"draft"};
async function readJson<T>(response:Response):Promise<T>{return await response.json() as T}

export default function AdminClient({ email, signOutPath }: { email:string; signOutPath:string }) {
  const [data, setData] = useState<{products:Product[]; requests:ServiceRequest[]; orders:Order[];secondHand:SecondHand[];posts:Post[];brands:Taxonomy[];categories:Taxonomy[]}>({products:[],requests:[],orders:[],secondHand:[],posts:[],brands:[],categories:[]});
  const [form, setForm] = useState(initial); const [message, setMessage] = useState("Yükleniyor…");
  const [editing,setEditing]=useState<Product|null>(null); const [secondForm,setSecondForm]=useState(secondInitial); const [postForm,setPostForm]=useState(postInitial); const [taxonomyForm,setTaxonomyForm]=useState({type:"category",name:"",slug:""});
  const [imageUpload,setImageUpload]=useState<{status:"idle"|"uploading"|"error";error?:string}>({status:"idle"});
  const load = useCallback(async () => { const r=await fetch("/api/admin/overview"); const json=await readJson<{products:Product[];requests:ServiceRequest[];orders:Order[];secondHand:SecondHand[];posts:Post[];brands:Taxonomy[];categories:Taxonomy[];error?:string}>(r); if(r.ok){setData(json);setMessage("")}else setMessage(json.error||"Veriler alınamadı") }, []);
  useEffect(()=>{
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  async function createProduct(e:React.FormEvent){e.preventDefault();setMessage("Ürün kaydediliyor…");const r=await fetch("/api/admin/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const j=await readJson<{error?:string}>(r);if(!r.ok){setMessage(j.error||"Kayıt başarısız");return}setForm(initial);setMessage("Ürün kaydedildi.");await load()}
  async function updateProduct(id:string, patch:object){setMessage("Güncelleniyor…");const r=await fetch(`/api/admin/products/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});if(r.ok){await load()}else setMessage("Güncelleme başarısız")}
  async function archiveProduct(id:string){if(!confirm("Ürün yayından kaldırılıp stok dışı yapılsın mı?"))return;await fetch(`/api/admin/products/${id}`,{method:"DELETE"});setEditing(null);await load()}
  async function uploadProductImage(id:string,file:File){setImageUpload({status:"uploading"});const body=new FormData();body.append("file",file);const r=await fetch(`/api/admin/products/${id}/image`,{method:"POST",body});const j=await readJson<{error?:string;imageUrl?:string}>(r);if(!r.ok||!j.imageUrl){setImageUpload({status:"error",error:j.error||"Görsel yüklenemedi."});return}setImageUpload({status:"idle"});setEditing(v=>v&&v.id===id?{...v,imageUrl:j.imageUrl!}:v);await load()}
  async function createSecond(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/second-hand",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(secondForm)});const j=await readJson<{error?:string}>(r);if(!r.ok){setMessage(j.error||"Kayıt başarısız");return}setSecondForm(secondInitial);await load();setMessage("İkinci el ürün kaydedildi.")}
  async function updateSecond(id:string,patch:object){await fetch(`/api/admin/second-hand/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});await load()}
  async function createPost(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/blog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(postForm)});const j=await readJson<{error?:string}>(r);if(!r.ok){setMessage(j.error||"Yazı kaydedilemedi");return}setPostForm(postInitial);await load();setMessage("Blog yazısı kaydedildi.")}
  async function updatePost(id:string,patch:object){await fetch(`/api/admin/blog/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});await load()}
  async function updateRequest(id:string,status:string){await fetch(`/api/admin/service-requests/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});await load()}
  async function importCatalog(){setMessage("GREE kataloğu veritabanına aktarılıyor…");const r=await fetch("/api/admin/catalog/import",{method:"POST"});const j=await readJson<{error?:string;total?:number;inserted?:number}>(r);if(!r.ok){setMessage(j.error||"Katalog aktarılamadı");return}await load();setMessage(`${j.total??0} katalog kaydı kontrol edildi; ${j.inserted??0} eksik ürün eklendi.`)}
  async function updateOrder(id:string,status:string){const r=await fetch(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(!r.ok){setMessage("Sipariş durumu güncellenemedi");return}await load()}
  async function createTaxonomy(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/taxonomy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(taxonomyForm)});const j=await readJson<{error?:string}>(r);if(!r.ok){setMessage(j.error||"Kayıt başarısız");return}setTaxonomyForm({type:"category",name:"",slug:""});await load();setMessage("Marka/kategori kaydedildi.")}
  async function toggleTaxonomy(type:"brand"|"category",item:Taxonomy){await fetch("/api/admin/taxonomy",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type,id:item.id,active:!item.active})});await load()}
  const set=(key:string,value:string|number)=>setForm(v=>({...v,[key]:value}));
  return <main className="min-h-screen bg-[#f4f8f6] text-[#10251f]">
    <header className="border-b bg-[#07261d] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><p className="text-xs font-bold tracking-[.18em] text-emerald-300">EGE TEKNİK</p><h1 className="text-2xl font-bold">Yönetim Merkezi</h1></div><div className="text-right text-sm"><p>{email}</p><div className="mt-1 flex items-center gap-3"><Link href="/index.html" className="text-emerald-300">Siteyi aç</Link><form method="post" action={signOutPath}><button className="text-emerald-300">Çıkış</button></form></div></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 py-7">
      <section className="grid gap-4 sm:grid-cols-4"><Stat label="Veritabanı" value="Bağlı"/><Stat label="Ürün" value={data.products.length}/><Stat label="Açık talep" value={data.requests.filter(x=>!["completed","cancelled"].includes(x.status)).length}/><Stat label="Sipariş" value={data.orders.length}/></section>
      {message&&<p className="rounded-lg bg-amber-100 px-4 py-3 text-sm">{message}</p>}
      <Card><CardHeader className="flex-row items-center justify-between gap-4"><div><CardTitle>Ürün kataloğu</CardTitle><p className="mt-1 text-sm text-zinc-500">Fiyat, stok ve yayın bilgileri doğrudan canlı veritabanında tutulur.</p></div><Button type="button" variant="outline" onClick={importCatalog}>GREE kataloğunu yükle</Button></CardHeader><CardContent><h3 className="mb-4 font-semibold">Yeni ürün ekle</h3><form onSubmit={createProduct} className="grid gap-4 md:grid-cols-4">
        {[["Ürün adı","name"],["URL kısa adı","slug"],["Kategori","category"],["Seri","series"],["SKU","sku"],["Kapasite","capacity"],["Enerji sınıfı","energyClass"],["Wi-Fi","wifi"]].map(([label,key])=><div key={key}><Label>{label}</Label><Input required={key==="name"||key==="slug"||key==="category"} value={String(form[key as keyof typeof form])} onChange={e=>set(key,e.target.value)}/></div>)}
        <div><Label>Fiyat (TL)</Label><Input type="number" min="0" value={form.price} onChange={e=>set("price",Number(e.target.value))}/></div><div><Label>Stok</Label><Input type="number" min="0" value={form.stock} onChange={e=>set("stock",Number(e.target.value))}/></div>
        <div><Label>Marka</Label><select className="h-9 w-full rounded-md border bg-white px-3" value={form.brandId??""} onChange={e=>setForm({...form,brandId:e.target.value||null})}><option value="">Seçin</option>{data.brands.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
        <div><Label>Kategori kaydı</Label><select className="h-9 w-full rounded-md border bg-white px-3" value={form.categoryId??""} onChange={e=>setForm({...form,categoryId:e.target.value||null})}><option value="">Seçin</option>{data.categories.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
        <div><Label>Satış biçimi</Label><select className="h-9 w-full rounded-md border bg-white px-3" value={form.saleMode} onChange={e=>set("saleMode",e.target.value)}><option value="quote">Teklif</option><option value="online">Online</option><option value="discovery">Keşif</option><option value="whatsapp">WhatsApp</option><option value="out_of_stock">Stok dışı</option></select></div>
        <div><Label>Yayın</Label><select className="h-9 w-full rounded-md border bg-white px-3" value={form.status} onChange={e=>set("status",e.target.value)}><option value="draft">Taslak</option><option value="published">Yayında</option></select></div>
        <div className="md:col-span-4"><Label>Açıklama</Label><Textarea value={form.description} onChange={e=>set("description",e.target.value)}/></div><Button className="md:col-span-1">Ürünü kaydet</Button>
        <div className="md:col-span-3"><Label>Ürün görseli URL</Label><Input type="url" placeholder="https://..." value={form.imageUrl} onChange={e=>set("imageUrl",e.target.value)}/>{form.imageUrl&&<small className="text-emerald-700">Görsel URL&apos;si hazır</small>}</div>
      </form></CardContent></Card>
      <Card><CardHeader><CardTitle>Ürün ve stok yönetimi</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Ürün</TableHead><TableHead>Kategori</TableHead><TableHead>Stok</TableHead><TableHead>Fiyat</TableHead><TableHead>Durum</TableHead><TableHead>İşlem</TableHead></TableRow></TableHeader><TableBody>{data.products.map(p=><TableRow key={p.id}><TableCell><b>{p.name}</b></TableCell><TableCell>{p.category}</TableCell><TableCell><Input className="w-20" type="number" defaultValue={p.stock} onBlur={e=>updateProduct(p.id,{stock:Number(e.target.value)})}/></TableCell><TableCell><Input className="w-28" type="number" defaultValue={p.price} onBlur={e=>updateProduct(p.id,{price:Number(e.target.value)})}/></TableCell><TableCell><select value={p.status} onChange={e=>updateProduct(p.id,{status:e.target.value})} className="rounded border p-2"><option value="draft">Taslak</option><option value="published">Yayında</option></select></TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{setEditing({...p});setImageUpload({status:"idle"})}}>Düzenle</Button></TableCell></TableRow>)}</TableBody></Table>
      {editing&&<form className="mt-6 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3" onSubmit={async e=>{e.preventDefault();await updateProduct(editing.id,editing);setEditing(null)}}><h3 className="md:col-span-3 font-bold">Ürünü düzenle</h3>{(["name","slug","category","series","sku","capacity","energyClass","wifi"] as const).map(k=><div key={k}><Label>{k}</Label><Input value={String(editing[k])} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></div>)}<div className="md:col-span-3"><Label>Açıklama</Label><Textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></div><Input type="url" placeholder="Görsel URL" value={editing.imageUrl} onChange={e=>setEditing({...editing,imageUrl:e.target.value})}/>
      <div className="md:col-span-3 flex flex-wrap items-center gap-3">
        <input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={imageUpload.status==="uploading"} onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(file)void uploadProductImage(editing.id,file)}}/>
        {imageUpload.status==="uploading"&&<small className="text-zinc-500">Görsel yükleniyor…</small>}
        {imageUpload.status==="error"&&<small className="text-red-600">{imageUpload.error}</small>}
        {imageUpload.status==="idle"&&editing.imageUrl&&<small className="text-emerald-700">Görsel hazır</small>}
      </div>
      <Button>Değişiklikleri kaydet</Button><Button type="button" variant="destructive" onClick={()=>archiveProduct(editing.id)}>Yayından kaldır</Button></form>}
      </CardContent></Card>
      <Card><CardHeader><CardTitle>Marka ve kategori yönetimi</CardTitle></CardHeader><CardContent><form onSubmit={createTaxonomy} className="grid gap-3 md:grid-cols-4"><select className="h-9 rounded border" value={taxonomyForm.type} onChange={e=>setTaxonomyForm({...taxonomyForm,type:e.target.value})}><option value="category">Kategori</option><option value="brand">Marka</option></select><Input required placeholder="Ad" value={taxonomyForm.name} onChange={e=>setTaxonomyForm({...taxonomyForm,name:e.target.value})}/><Input required pattern="[a-z0-9-]+" placeholder="url-kisa-adi" value={taxonomyForm.slug} onChange={e=>setTaxonomyForm({...taxonomyForm,slug:e.target.value})}/><Button>Kaydet</Button></form><div className="mt-4 flex flex-wrap gap-2">{data.brands.map(x=><Button key={x.id} size="sm" variant="outline" onClick={()=>toggleTaxonomy("brand",x)}>{x.name}: {x.active?"aktif":"pasif"}</Button>)}{data.categories.map(x=><Button key={x.id} size="sm" variant="outline" onClick={()=>toggleTaxonomy("category",x)}>{x.name}: {x.active?"aktif":"pasif"}</Button>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>İkinci el ve outlet stokları</CardTitle></CardHeader><CardContent><form onSubmit={createSecond} className="grid gap-3 md:grid-cols-4">{([['Ad','name'],['URL kısa adı','slug'],['Kategori','category'],['Kondisyon','condition'],['Garanti','warranty']] as const).map(([l,k])=><div key={k}><Label>{l}</Label><Input required={k==='name'||k==='slug'||k==='category'} value={String(secondForm[k])} onChange={e=>setSecondForm({...secondForm,[k]:e.target.value})}/></div>)}<div><Label>Fiyat</Label><Input type="number" value={secondForm.price} onChange={e=>setSecondForm({...secondForm,price:Number(e.target.value)})}/></div><div><Label>Stok</Label><Input type="number" value={secondForm.stock} onChange={e=>setSecondForm({...secondForm,stock:Number(e.target.value)})}/></div><div><Label>Durum</Label><select className="h-9 w-full rounded border" value={secondForm.status} onChange={e=>setSecondForm({...secondForm,status:e.target.value})}><option value="draft">Taslak</option><option value="published">Yayında</option><option value="sold">Satıldı</option></select></div><div className="md:col-span-2"><Label>Test notları</Label><Textarea value={secondForm.testNotes} onChange={e=>setSecondForm({...secondForm,testNotes:e.target.value})}/></div><div className="md:col-span-2"><Label>Açıklama</Label><Textarea value={secondForm.description} onChange={e=>setSecondForm({...secondForm,description:e.target.value})}/></div><Input type="url" placeholder="Görsel URL" value={secondForm.imageUrl} onChange={e=>setSecondForm({...secondForm,imageUrl:e.target.value})}/><Button>İkinci el ürünü ekle</Button></form><div className="mt-5 grid gap-2">{data.secondHand.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><b>{x.name}</b><span>{x.stock} adet · {x.price} TL</span><select value={x.status} onChange={e=>updateSecond(x.id,{status:e.target.value})} className="rounded border p-2"><option value="draft">Taslak</option><option value="published">Yayında</option><option value="sold">Satıldı</option></select></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Blog CMS</CardTitle></CardHeader><CardContent><form onSubmit={createPost} className="grid gap-3 md:grid-cols-2"><div><Label>Başlık</Label><Input required value={postForm.title} onChange={e=>setPostForm({...postForm,title:e.target.value})}/></div><div><Label>URL kısa adı</Label><Input required value={postForm.slug} onChange={e=>setPostForm({...postForm,slug:e.target.value})}/></div><div className="md:col-span-2"><Label>Özet</Label><Textarea value={postForm.excerpt} onChange={e=>setPostForm({...postForm,excerpt:e.target.value})}/></div><div className="md:col-span-2"><Label>Yazı içeriği</Label><Textarea className="min-h-52" required value={postForm.content} onChange={e=>setPostForm({...postForm,content:e.target.value})}/></div><Input type="url" placeholder="Görsel URL" value={postForm.imageUrl} onChange={e=>setPostForm({...postForm,imageUrl:e.target.value})}/><select className="h-9 rounded border" value={postForm.status} onChange={e=>setPostForm({...postForm,status:e.target.value})}><option value="draft">Taslak</option><option value="published">Yayında</option></select><Button>Yazıyı kaydet</Button></form><div className="mt-5 grid gap-2">{data.posts.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><b>{x.title}</b><select value={x.status} onChange={e=>updatePost(x.id,{status:e.target.value})} className="rounded border p-2"><option value="draft">Taslak</option><option value="published">Yayında</option></select></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Servis ve keşif talepleri</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>No / Tarih</TableHead><TableHead>Müşteri</TableHead><TableHead>Talep</TableHead><TableHead>Durum</TableHead></TableRow></TableHeader><TableBody>{data.requests.map(r=><TableRow key={r.id}><TableCell><b>{r.requestNumber}</b><br/><small>{r.createdAt}</small></TableCell><TableCell>{r.name}<br/><a className="text-emerald-700" href={`tel:${r.phone}`}>{r.phone}</a><br/><small>{r.city}</small></TableCell><TableCell className="max-w-lg whitespace-normal"><b>{r.type}</b><br/>{r.message}</TableCell><TableCell><select value={r.status} onChange={e=>updateRequest(r.id,e.target.value)} className="rounded border p-2"><option value="new">Yeni</option><option value="contacted">Arandı</option><option value="scheduled">Planlandı</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option></select></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      <Card><CardHeader><CardTitle>Siparişler</CardTitle></CardHeader><CardContent>{data.orders.length?<Table><TableHeader><TableRow><TableHead>Sipariş</TableHead><TableHead>Müşteri</TableHead><TableHead>Tutar</TableHead><TableHead>Durum</TableHead></TableRow></TableHeader><TableBody>{data.orders.map(o=><TableRow key={o.id}><TableCell><b>{o.orderNumber}</b><br/><small>{o.createdAt}</small></TableCell><TableCell>{o.customerName}</TableCell><TableCell>{new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(o.total)}</TableCell><TableCell><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value)} className="rounded border p-2"><option value="pending_payment">Ödeme bekliyor</option><option value="paid">Ödendi</option><option value="preparing">Hazırlanıyor</option><option value="shipped">Kargoya verildi</option><option value="delivery">Teslimat</option><option value="delivered">Teslim edildi</option><option value="installation">Montaj</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option><option value="returned">İade</option><option value="service">Servis</option></select></TableCell></TableRow>)}</TableBody></Table>:<p className="text-sm text-zinc-500">Henüz sipariş yok.</p>}</CardContent></Card>
    </div>
  </main>
}

function Stat({label,value}:{label:string;value:number|string}){return <Card><CardContent className="pt-6"><p className="text-sm text-zinc-500">{label}</p><p className="text-3xl font-bold">{value}</p></CardContent></Card>}
