import { getDb } from "@/db";
import { rateLimitBuckets } from "@/db/schema";
import { eq, sql } from "drizzle-orm";
import { clientIp, hashWithSecret } from "@/lib/admin-auth";

export function safeError(status=500,message="İşlem tamamlanamadı."){return Response.json({error:message},{status})}
const prohibitedCardKeys=/^(pan|card_?number|credit_?card|cvv|cvc|expiry|expiration|expiration_?date)$/i;
function containsCardData(value:unknown):boolean{if(!value||typeof value!=="object")return false;if(Array.isArray(value))return value.some(containsCardData);return Object.entries(value).some(([key,item])=>prohibitedCardKeys.test(key)||containsCardData(item))}
export async function readJson(request:Request,maxBytes=32_000){const length=Number(request.headers.get("content-length")||0);if(length>maxBytes)throw new HttpError(413,"İstek boyutu çok büyük.");const text=await request.text();if(new TextEncoder().encode(text).byteLength>maxBytes)throw new HttpError(413,"İstek boyutu çok büyük.");try{const value=JSON.parse(text) as unknown;if(containsCardData(value))throw new HttpError(400,"Kart verisi bu sistem tarafından kabul edilmez.");return value}catch(error){if(error instanceof HttpError)throw error;throw new HttpError(400,"Geçersiz JSON.")}}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function assertSameOrigin(request:Request){const origin=request.headers.get("origin"),host=request.headers.get("x-forwarded-host")||request.headers.get("host");if(!origin||!host)throw new HttpError(403,"İstek kaynağı doğrulanamadı.");let originHost="";try{originHost=new URL(origin).host}catch{}if(originHost!==host)throw new HttpError(403,"İstek kaynağı reddedildi.")}
export async function rateLimit(request:Request,scope:string,limit:number,windowMs:number){const key=`${scope}:${await hashWithSecret(clientIp(request))}`,db=getDb(),now=new Date(),expiresAt=new Date(now.getTime()+windowMs);const [bucket]=await db.select().from(rateLimitBuckets).where(eq(rateLimitBuckets.key,key)).limit(1);if(bucket&&bucket.expiresAt>now&&bucket.count>=limit)throw new HttpError(429,"Çok fazla istek gönderildi. Lütfen daha sonra tekrar deneyin.");await db.insert(rateLimitBuckets).values({key,count:1,windowStartedAt:now,expiresAt}).onConflictDoUpdate({target:rateLimitBuckets.key,set:bucket&&bucket.expiresAt>now?{count:sql`${rateLimitBuckets.count}+1`}:{count:1,windowStartedAt:now,expiresAt}})}
export function publicRoute(handler:(request:Request)=>Promise<Response>){return async(request:Request)=>{try{return await handler(request)}catch(error){if(error instanceof HttpError)return safeError(error.status,error.message);console.error("public_route_error",{name:error instanceof Error?error.name:"unknown"});return safeError()}}}
